### ISSUE TITLE
pip install eigency fails with ModuleNotFoundError: No module named 'numpy'

### ISSUE THREAD

**Issue by pfaion** [wouterboomsma/eigency#34]
I noticed that you have to install numpy before being able to install eigency, otherwise the installations fails (see log below). This is due to eigency using numpy in the build phase and not (yet) specifying build system requirements in a pyproject.toml as described by [PEP517](https://www.python.org/dev/peps/pep-0517/) / [PEP518](https://www.python.org/dev/peps/pep-0518/).

This can result in libraries depending on eigency also failing to install when they are installed without numpy already present, even if those libraries specify numpy as build system requirement.

Error log:
```
> pip install eigency

Collecting eigency
  Using cached eigency-1.77.tar.gz (678 kB)
    ERROR: Command errored out with exit status 1:
     command: /home/patrick/.pyenv/versions/3.7.7/envs/pupil/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bfnvr5bv/eigency/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bfnvr5bv/eigency/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-bfnvr5bv/eigency/pip-egg-info
         cwd: /tmp/pip-install-bfnvr5bv/eigency/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-bfnvr5bv/eigency/setup.py", line 6, in <module>
        import eigency
      File "/tmp/pip-install-bfnvr5bv/eigency/eigency/__init__.py", line 2, in <module>
        import numpy as np
    ModuleNotFoundError: No module named 'numpy'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by lacava** [comment]
this would also fix issue https://github.com/wouterboomsma/eigency/issues/16
